name: one_bark_plaza
description: One Bark Plaza
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  http: "^0.12.0+4"
  dynamic_widget: "^0.0.3"
  dio: ^3.0.9
  intl: ^0.16.1
  toast: ^0.1.5
  flutter_spinkit: "4.1.2+1"
  cached_network_image: "^2.0.0"
  shared_preferences : "^0.5.6+2"
  flutter_email_sender : "^2.2.2"
  connectivity : "^0.4.8+2"
  pull_to_refresh: ^1.5.7
  file_picker: ^1.6.2
  multi_image_picker: ^4.6.5+rc.1
  carousel_slider: ^1.3.0
  cupertino_range_slider: ^1.0.1
  native_pdf_renderer: ^1.8.1
  mime: ^0.9.6+3
  open_file: ^3.0.1
  flutter_absolute_path: ^1.0.6
  url_launcher: ^5.4.2
  image_picker: ^0.6.5+2
  image_cropper: ^1.2.1
  path_provider:
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.4"
  flutter_test:
    sdk: flutter


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/onebark_logo_foreground.png"
  image_path_android: "assets/images/onebark_logo_foreground.png"
  adaptive_icon_background: "assets/images/onebark_logo_background.png"
  adaptive_icon_foreground: "assets/images/onebark_logo_foreground.png"

flutter:
  assets:
    - assets/images/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf

  uses-material-design: true